[platformio]
default_envs = Upload_UART

[env]
platform = atmelavr
framework = arduino

; TARGET
board = ATmega328P
board_build.f_cpu = 16000000L

; Serial Monitor (optional)
monitor_speed = 9600


; ---------- Upload over USB-serial (bootloader) ----------
[env:Upload_UART]
upload_protocol = urclock

; Usually auto-detected. If not:
; Windows: upload_port = COM5
; Linux:   upload_port = /dev/ttyUSB0
; macOS:   upload_port = /dev/cu.usbserial-*
upload_port = /dev/ttyUSB0
